### ISSUE TITLE
TableRates option offered for $0 if no matches

### ISSUE THREAD

**Issue by isaacniebeling** [modmore/Commerce_TableRates#3]
If there is no match in a TableRates table, the shipping method is offered for $0 during the checkout process. I _think_ the expected behavior according to the TableRates docs is that there should be a ~~final~~ first row added by the user that matches everything (`*,*,*,*,price` or whatever, potentially restricted by country code in the first column). 

I believe that the shipping method shouldn't be offered at all if there's no match; there are potentially two places this should be checked:

1. TableRatesShippingMethod::getPriceForShipment() should be checking whether `$options` is empty around line 362, probably
2. TableRatesShippingMethod::isAvailableForShipment() should be calling `getMatchingOptions` / `getMatchFor[type, eventually, but just weight right now]` and checking to make sure there's a valid shipping option. 

For backwards compatibility, we may want to either run a one-time upgrade script to check for TableRates shipping options and add the `*,*,*,*,0` line to all TableRates configurations, or add a default-on checkbox to the shipping method configuration screen to allow the method to be shown for $0 if there's no match. If the module isn't used much, we MAY be able to get away with just putting a note in the changelog, or doing a _check_ to list any shipping methods with no final line but not actually update it.

**Comment by isaacniebeling** [comment]
Sorry, I was misremembering how Table Rates works when I said there should be a final matching row; it should actually be the FIRST row, because Table Rates returns the LAST applicable row, and that would mean that the least-specific rule would always be returned 😂

**Comment by Mark-H** [comment]
You can set the regular price on the shipping method - that would be used if there are no matches.

**Comment by isaacniebeling** [comment]
How would one disable the shipping method if there are no matches?

**Comment by isaacniebeling** [comment]
Any thoughts on this? I have no expectations of an answer at this point on a Friday, just figured I'd poke it while I was thinking of it 😂

**Comment by Mark-H** [comment]
Sorry I've been too busy with the modmore site to look into it. It does sound like you're correct and that #5 will help somewhat (maybe not this issue specifically) but will need to test and see things locally to make sense of it.
